locals {
  # Datadog APM parser configurations
  # These parsers handle Datadog APM trace logs generated by the application
  datadog_parsers = [
    {
      name        = "datadog_json"
      format      = "json"
      time_key    = "datetime"
      time_format = "%Y-%m-%dT%H:%M:%S%z"
      time_keep   = false
      filter = {
        match        = "*" # Will be overridden by container-specific pattern
        key_name     = "log"
        reserve_data = true
        preserve_key = false
        unescape_key = false
      }
    }
  ]

  # Datadog APM filter configurations
  # Only accept logs containing APM trace information
  datadog_filters = [
    {
      name  = "grep"
      match = "*" # Will be overridden by container-specific pattern
      regex = "log Luscii APM"
    },
    {
      name  = "modify"
      match = "*" # Will be overridden by container-specific pattern
      add_fields = {
        log_source = "datadog"
      }
    }
  ]

  # Map entry for this technology
  datadog_parsers_map = {
    datadog = local.datadog_parsers
  }

  datadog_filters_map = {
    datadog = local.datadog_filters
  }
}
